kind: pipeline
name: drone
steps:
  - name: restoreCache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: npmInstall
    image: node:10
    commands:
      - npm config set cache ./.npm-cache --global
      - npm install

  - name: build-dist
    image: node:10
    commands:
      - npm run build

  - name: rebuildCache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./.npm-cache
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: build
    image: plugins/docker
    repo: testadmin/testadmin
    tags: [1]
  volumes:
    - name: cache
      host:
        path: /tmp/cache
