version: "3"
networks:
  default:
    external:
      name: default-network
services:
  myapp:
    container_name: drone-reactAdmin
    image: swr.cn-north-1.myhuaweicloud.com/a82253452/reactAdmin
    labels:
      - traefik.http.routers.reactAdmin-http.rule=Host(`zhihuizhan.net` && PathPrefix(`/admin`))
      - traefik.http.routers.reactAdmin.rule=Host(`zhihuizhan.net` && PathPrefix(`/admin`))
      - traefik.http.routers.reactAdmin.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.strip-prefix-admin.stripprefix.prefixes=/admin
      - traefik.http.routers.comapi.middlewares=strip-prefix-admin@docker
