version: "3"
networks:
  default:
    external:
      name: default-network
services:
  testadmin:
    container_name: testadmin
    image: swr.cn-north-1.myhuaweicloud.com/a82253452/testadmin
    ports:
      - 8010:80
